services:
  web:
    build: .
    command: ./entrypoint.sh  # Handle starting both servers here
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Always mount the app directory
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    extra_hosts:
      - "bot.com:127.0.0.1"  # This maps bot.com to localhost
