services:
  web:
    build: .
    command: ./entrypoint.sh  # Handle starting both servers here
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /home/ed/.local/lib/python3.8/site-packages:/usr/local/lib/python3.8/site-packages  # Mount Selenium
      - /usr/bin/chromedriver:/usr/bin/chromedriver  # Mount ChromeDriver
      - /usr/bin/google-chrome:/usr/bin/google-chrome  # Mount Chrome
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    extra_hosts:
      - "bot.com:127.0.0.1"  # This maps bot.com to localhost

