services:
  web:
    build: .
    command: ./entrypoint.sh
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /usr/bin/google-chrome:/usr/bin/google-chrome  # Mount Chrome from the host
      - /usr/local/bin/chromedriver:/usr/local/bin/chromedriver  # Mount ChromeDriver from the host
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    extra_hosts:
      - "bot.com:127.0.0.1"
